default:
  target: redshift
  outputs:
    redshift:
      type: redshift
      threads: 1
      host: "{{ env_var('REDSHIFT_HOST') }}"
      port: "{{ env_var('REDSHIFT_PORT') | as_number }}"
      user: "{{ env_var('REDSHIFT_USERNAME') }}"
      pass: "{{ env_var('REDSHIFT_PASSWORD') }}"
      dbname: "{{ env_var('REDSHIFT_DBNAME') }}"
      schema: "{{ env_var('REDSHIFT_SCHEMA') }}"
