[tool.poetry]
name = "revenues-ccy"
version = "0.1.0"
description = "Calculate Revenues CCY for financial area"
authors = ["dmartin <next.dmartin@iberia.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
dbt-redshift = "1.6.2"

[tool.poetry.group.dev.dependencies]
sqlfluff = "^2.1.1"
dbt-junitxml = {git = "https://github.com/SOVALINUX/dbt-junitxml", rev = "0.2.1"}  # Fork compatible con DBT Core 1.3+networkx = "2.6.2"
mkdocs = "1.2.4"
mkdocs-material = "7.3.0"
mkdocs-print-site-plugin="2.0.0"
pymdown-extensions = "9.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.sqlfluff.core]
ignore = "templating"
dialect = "redshift"
exclude_rules = "L031, L044, L051, L059, L034, L001, L016, L057, L029, L011"
large_file_skip_byte_limit = 20500

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.functions]
extended_capitalisation_policy = "lower"

[tool.sqlfluff.indentation]
indented_joins = "True"
